INSERT INTO CRM_SEQUENCE (INCOMING_ID, OUTGOING_ID)
VALUES (1,15);
INSERT INTO CRM_SEQUENCE (INCOMING_ID, OUTGOING_ID)
VALUES (2,16);
INSERT INTO CRM_SEQUENCE (INCOMING_ID, OUTGOING_ID)
VALUES (8,17);


SELECT * FROM CRM_SEQUENCE