select a.INCOMING_ID,a.OUTGOING_ID,b.CONTACT_DESCRIPTOR,c.CONTACT_DESCRIPTOR 
from CRM_SEQUENCE a join CRM_CONT_TYPE b
on a.INCOMING_ID=b.INCOMING_ID
and  a. CONTACT_ID=b.CONTACT_ID
join CRM_CONT_TYPE c 
on a.OUTGOING_ID=c.OUTGOING_ID
and c.CONTACT_ID=a.CONTACT_ID
